---
- hosts: NetworkClient
  vars_files: 
  - roles/qperf/vars/main.yml  
  tasks:
    - name: remove latest data
      file:    
        path: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/ 
        state: absent
 
    - name: run qperf on client  
      command: qperf -oo msg_size:1:64K:*2 {{server_addr}} tcp_bw tcp_lat
      register: logdata

    - lineinfile: create=yes  dest=~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/qper_output.txt line="{{ logdata.stdout }}" state=present

    - name: mkdir result
      file: dest=~/result state=directory

    - name: fetch result
      fetch:
        src: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/qper_output.txt  
        dest: ~/{{root_dir}}/{{app_dir}}/{{app_name_dir}}/{{app_test_tool_dir}}/result/qper_output.txt
        flat: yes

