---
- name: Install Network performance test tools including qperf
  hosts: NetworkClient
  remote_user: root
  roles:
    - qperf

- name: Install qperf server on ARM64Server
  hosts: NetworkServerD05
  remote_user: root
  roles:
    - qperf


