---
#
# Due to LVS provisioning, the JMeterClient host could not talk with Solr host directly.
# So the solr_benchmark_dataload will be performed on Solr host rather than JMeterClient.
# However the final test is still performed on JMeterClient
#
- name: Setup JMeter 
  hosts: JMeterClient 
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  vars:
    pcp_pmcd: false
    pcp_web_vector: true
    jmeter_version: "3.2"
  roles:
    - estuaryrepo
    - { role: openjdk }
    - { role: jmeter }
    - { role: pcp }

- name: Load Solr Data 
  hosts: ARM64Server06
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  vars:
    solr_server: "192.168.11.219"
    solr_port: 8983
  roles:
    - estuaryrepo
    - { role: openjdk }
    - { role: solr_benchmark_setup }
    - { role: solr_benchmark_dataload }

- name: Load Cart Data
  hosts: ARM64MySQLCartDATA
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  vars:
     database: e-commerce-cart
     sql_location: /opt/data/
     listen_port: 3306
     login_host: "{{ ansible_eth2['ipv4']['address'] }}"
     login_name: root
     login_password:
     cart: cart.sql
     userinfo: r_ec_userinfo.sql
     sku: r_ec_sku.sql
     sku_supplement: r_ec_sku_supplement.sql
     userbank: r_ec_userbankinfo.sql
  roles:
    - estuaryrepo
    - { role: percona-server-data }

- name: Load Order Data
  hosts: ARM64MySQLOrderDATA 
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  vars: 
     database: e-commerce-order
     sql_location: /opt/data/
     listen_port: 3306
     login_host: "{{ ansible_eth2['ipv4']['address'] }}"
     login_name: root
     login_password:
     order: order.sql
     userinfo: r_ec_userinfo.sql
     sku: r_ec_sku.sql
     sku_supplement: r_ec_sku_supplement.sql
     userbank: r_ec_userbankinfo.sql
     userdeliveryaddress: r_ec_userdeliveryaddress.sql
  roles:
    - estuaryrepo
    - { role: percona-server-data }

- name: load redis data
  hosts: ARM64REDISSEARCHDATA
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - redis-data

